package entities.enums;


public enum OrderStatus { //SAO CONTANSTES
	
	PENDING_PAYMENT, // PAGAMENTO PENDENTE
	PROCESSING, // PROCESSANDO
	SHIPPED, // DESPACHADO
	DELIVERED; //ENTREGUE

}
